"use client"
import { TaskProvider } from '@/context/TasksContext'
import { Toaster } from '@/app/Toaster'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar';
import { Layout } from '@/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TaskProvider>
          <NavBar />
          <Layout>{children}</Layout>
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  )
}
